package cmd

import (
	"context"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"

	"github.com/robsonek/berth/internal/config"
	bssh "github.com/robsonek/berth/internal/ssh"
	"github.com/robsonek/berth/internal/ui"
)

func newSiteCmd() *cobra.Command {
	c := &cobra.Command{Use: "site", Short: "Manage sites on a server"}
	c.AddCommand(&cobra.Command{
		Use:   "add <server>",
		Short: "Add another site to an existing server",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return errNotImplemented("site:add") // post-v1
		},
	})
	c.AddCommand(newSiteKeyCmd())
	return c
}

func newSiteKeyCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "key <server> [domain]",
		Short: "Print a site's git deploy public key (paste it into the repo host)",
		Args:  cobra.RangeArgs(1, 2),
		RunE: func(cmd *cobra.Command, args []string) error {
			srv, err := config.Load(args[0])
			if err != nil {
				return err
			}
			domain := ""
			if len(args) == 2 {
				domain = args[1]
			}
			client, err := bssh.Connect(cmd.Context(), srv, bssh.HostKeyPolicy{
				Pinned: srv.SSH.Fingerprint, KnownHosts: defaultKnownHosts(),
				AllowTOFU: ui.IsTTY(os.Stdin), ConfirmTOFU: confirmFingerprint(cmd),
			})
			if err != nil {
				return err
			}
			defer client.Close()
			return printDeployKeys(cmd.Context(), cmd.OutOrStdout(), srv, client, domain)
		},
	}
}

// printDeployKeys writes each selected site's deploy public key — generated by
// the accounts step for sites with a repository — to out. Read-only: it never
// generates or mutates anything. A site without a repository has no managed
// key by design; a missing key file means the host was not provisioned yet.
// The site user is validated (reLinuxUser, no shell metacharacters), so the
// cat command is stable and unquoted.
func printDeployKeys(ctx context.Context, out io.Writer, srv *config.Server, r bssh.Runner, domain string) error {
	sites := srv.Sites
	if domain != "" {
		sites = nil
		for _, site := range srv.Sites {
			if site.Domain == domain {
				sites = []config.Site{site}
				break
			}
		}
		if sites == nil {
			return fmt.Errorf("no site with domain %q in this config", domain)
		}
	}
	for _, site := range sites {
		user := srv.SiteUser(site)
		fmt.Fprintf(out, "# %s (user %s)\n", site.Domain, user)
		if site.Repository == "" {
			fmt.Fprintln(out, "no deploy key is managed for this site (set sites[].repository to have berth generate one)")
			continue
		}
		res, err := r.Run(ctx, "cat /home/"+user+"/.ssh/id_ed25519.pub", nil)
		if err != nil {
			return err
		}
		if res.ExitCode != 0 {
			fmt.Fprintln(out, "deploy key not generated yet — run `berth provision` first")
			continue
		}
		fmt.Fprintln(out, strings.TrimSpace(res.Stdout))
	}
	return nil
}
